# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='QuestionTitle', max_length=300),
        ),
    ]
