# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('core', '0004_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='QuestionTitle', help_text='A memorable identifier for the question', max_length=300),
        ),
    ]
