# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='nays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='yeas',
            field=models.IntegerField(default=0),
        ),
    ]
