# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170414_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
