# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170414_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_me',
        ),
    ]
