# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='correction',
            field=models.TextField(default='', max_length=500),
        ),
    ]
